[package]
name = "svgtypes"
# When updating version, also modify html_root_url in the lib.rs and in the README
version = "0.2.0"
authors = ["Reizner Evgeniy <razrfalcon@gmail.com>"]
keywords = ["svg", "parser", "tokenizer"]
categories = ["parsing"]
license = "MIT/Apache-2.0"
description = "SVG types parser and writer."
repository = "https://github.com/RazrFalcon/svgtypes"
documentation = "https://docs.rs/svgtypes/"
readme = "README.md"

[badges]
travis-ci = { repository = "RazrFalcon/svgtypes" }

[dependencies]
float-cmp = "0.4"
log = "0.4"
phf = "0.7.23"

[lib]
path = "src/lib.rs" # for cargo-readme
doctest = true
