[package]
name = "svgtypes"
# When updating version, also modify html_root_url in the lib.rs
version = "0.4.2"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
categories = ["parser-implementations"]
description = "SVG types parser and writer."
documentation = "https://docs.rs/svgtypes/"
keywords = ["svg", "parser", "tokenizer"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/RazrFalcon/svgtypes"

[workspace]
members = ["benches"]

[badges]
travis-ci = { repository = "RazrFalcon/svgtypes" }

[dependencies]
float-cmp = { version = "0.4.1", default-features = false }
phf = { version = "0.7.24", optional = true }

[features]
default = ["color", "attribute-id", "element-id"]
# The features below are requiring a large data tables, so if you don't plan to parse:
# Color, Paint, ElementId, AttributeId
# you can simply disable them.
color = ["phf"]
attribute-id = ["phf"]
element-id = ["phf"]

[package.metadata.docs.rs]
all-features = true

[lib]
path = "src/lib.rs" # for cargo-readme
doctest = true
