[package]
name = "svgtypes"
# When updating version, also modify html_root_url in the lib.rs
version = "0.4.1"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
categories = ["parser-implementations"]
description = "SVG types parser and writer."
documentation = "https://docs.rs/svgtypes/"
keywords = ["svg", "parser", "tokenizer"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/RazrFalcon/svgtypes"

[badges]
travis-ci = { repository = "RazrFalcon/svgtypes" }

[dependencies]
float-cmp = "0.4"
phf = "0.7.23"

[lib]
path = "src/lib.rs" # for cargo-readme
doctest = true
